### ISSUE TITLE
sample code on how to use

### ISSUE THREAD

**Issue by vizonyc** [valorekhov/node-ezsp-mqtt#1]
I have a matrix creator board which seems to work, program it is definitely getting info 

{"name":"uart","hostname":"raspberrypi","pid":2441,"level":20,"msg":"Data frame: 424bb1ee54aaea6e7895826b55aa6db662b1a4d31229688b02396889f77e2ff92bdcde6f39ca5885d7c123437e00","time":"2018-06-10T16:43:48.247Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2441,"level":20,"msg":"Sending: 8520dd7e","time":"2018-06-10T16:43:48.248Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2441,"level":20,"msg":"Application frame 70 (macFilterMatchMessageHandler) received","time":"2018-06-10T16:43:48.250Z","v":0}
 but I am not sure how to go from here. I was hoping to use this with node-red. I am not a coder but I think I can kluge something out with some direction

**Comment by valorekhov** [comment]
Have you been able to setup and validate a connection to an MQTT broker? You may install Mosquitto on your RPI if you already don't have it and follow instructions for creating a new dedicated user to be used with the EZSP gateway. After that you may use mosquitto-sub command to subscribe for updates to the rootTopic/# topic,  e.g. zbmq/# if using default rootTopic config, to see updates coming from your nodes. At the minimum, you should be able to see a message come through on the rootTopic/gatewayId/online topic when the gateway starts and successfully connects to the MQTT broker.

Additionally, you will need to be sure that the whatever ZigBee nodes you have are associated to your EZSP gateway, which acts as a coordinator. To allow the gateway to have other nodes join, you need to publish a message to the  rootTopic/gatewayId/permit-joining  with a payload containing the number of seconds for which joining is permitted. After that, follow steps specific to your node to initiate the joining sequence. Some XBees will automatically join provided they are configured as described in the "Interop With XBee Devices" section of the README.md

**Comment by vizonyc** [comment]
Thanks i think this will get me started will let you know how it goes
