### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by trsqr** [valorekhov/node-ezsp-mqtt#2]
This looks interesting. I'm looking to set up a Zigbee2MQTT system using my Telegesis ETRX357 stick. By default it does not have EZSP firmware, but as far as I can understand it can be flashed with one. 

Which device are you using and does it work out of the box or it needs flashing?

**Comment by valorekhov** [comment]
The project was developed with and is working on this [USB stick](https://nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/). It did not require any firmware changes and worked OTB.
