### ISSUE TITLE
Cannot get bulb to join

### ISSUE THREAD

**Issue by vizonyc** [valorekhov/node-ezsp-mqtt#3]
Using this with matrix creator : So far it sees the controller but I cant seem to get joins to work. Iwas able to use bellows https://github.com/zigpy/bellows to join the device and phillips hue-thief to reset but can t get joins to work.
my testing so far:
**mosquitto_pub -h localhost -p 1883 -t zbmq/000d6f000d07ad71/permit-joining -m {255}

Network ready
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Send command getNetworkParameters","time":"2018-08-28T04:31:18.444Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 004a2180faf37e","time":"2018-08-28T04:31:18.446Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Data frame: 0045b1b1c4beee7e","time":"2018-08-28T04:31:18.447Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 8160597e","time":"2018-08-28T04:31:18.448Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Application frame 25 (stackStatusHandler) received","time":"2018-08-28T04:31:18.449Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Data frame: 114aa180542be74c5a825c2562c8a637944127abedce677302c151da7e00","time":"2018-08-28T04:31:18.456Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 82503a7e","time":"2018-08-28T04:31:18.457Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Application frame 40 (getNetworkParameters) received","time":"2018-08-28T04:31:18.458Z","v":0}
{"name":"ezsp-mqtt","hostname":"raspberrypi","pid":2938,"level":30,"msg":"Ember Node Type: 1, EPAN ID: 0x9dc800161603fef2, PAN ID: 0x7e34","time":"2018-08-28T04:31:18.464Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Send command getEui64","time":"2018-08-28T04:31:18.465Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 124b218edac27e","time":"2018-08-28T04:31:18.467Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Data frame: 224ba18e258712bf59fb472522b07e","time":"2018-08-28T04:31:18.473Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 83401b7e","time":"2018-08-28T04:31:18.474Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Application frame 38 (getEui64) received","time":"2018-08-28T04:31:18.475Z","v":0}
{"name":"ezsp-mqtt","hostname":"raspberrypi","pid":2938,"level":30,"msg":"Gateway Topic: zbmq/000d6f000d07ad71","time":"2018-08-28T04:31:18.479Z","v":0}
{"name":"ezsp-mqtt","hostname":"raspberrypi","pid":2938,"level":30,"msg":"Started!","time":"2018-08-28T04:31:18.881Z","v":0}
{"name":"ezsp-mqtt","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Connected to mqtt://192.168.0.64","time":"2018-08-28T04:31:18.925Z","v":0}
{"name":"ezsp-mqtt","hostname":"raspberrypi","pid":2938,"level":50,"msg":"Received: zbmq/000d6f000d07ad71/permit-joining: {255}","time":"2018-08-28T04:31:31.505Z","v":0}
{"name":"ezsp-mqtt","hostname":"raspberrypi","pid":2938,"level":30,"msg":"Permitting joining for NaN seconds","time":"2018-08-28T04:31:31.507Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Send command permitJoining","time":"2018-08-28T04:31:31.508Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 2348218a5443e17e","time":"2018-08-28T04:31:31.510Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Data frame: 3348a18a547ce17e","time":"2018-08-28T04:31:31.515Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Sending: 8430fc7e","time":"2018-08-28T04:31:31.516Z","v":0}
{"name":"uart","hostname":"raspberrypi","pid":2938,"level":20,"msg":"Application frame 34 (permitJoining) received","time":"2018-08-28T04:31:31.517Z","v":0}**

Any ideas?

**Comment by vizonyc** [comment]
Ok I got it to work now to figure how to turn the ight off and on :)

**Comment by vizonyc** [comment]
How do I find what to publish to mqtt to control a device?

**Comment by valorekhov** [comment]
I've not integrated Hue myself. However, looking at the doc [here](https://www.developers.meethue.com/documentation/how-hue-works), it seems that Hue is compliant with Zigbee Light Link  spec.

You'll need to publish a message to the following topic 'zbmq/000d6f000d07ad71/**Long Address of the Bulb**/request' 
Assuming you paired the bulb successfully, check devices.json for the long address of the discovered bulb.

The _approximate_ message you want to publish is in the following format:
```json
 {"apsFrame":{"clusterId":6,"profileId":49246,"sourceEndpoint":0,"destinationEndpoint":11},"message":{"type":"Buffer","data":[255, 255, 255]}}
```
Where 49246/0xC05E is the profile ID of Zigbee Light LInk (ZLL).
Cluster ID of 6 and destinationEndpoint value of 11 / 0x0B are extracted from [here](https://github.com/ebaauw/homebridge-hue/wiki/ZigBee-Devices).
You will also have to figure out what to pass  via message.data array as I was not able to find the complete ZLL spec, however, you may download it from [here](https://www.zigbee.org/zigbee-for-developers/applicationstandards/zigbee-light-link/).

EZSP-MQTT gateway will simply pass on whatever JSON-encoded APS messages you send through it. Similar to what you'd have to do on other platforms, such as developing custom integration for a SmartHub, you'll need to figure out correct Cluster ID, source/destination endpoints and payload to pass for the device on the target end to do whatever it does.

**Comment by swilleyman** [comment]
I was having the same difficulty as @vizonyc attempting to control a Sengled Element bulb.  This bulb responds to commands in the same way as Philips Hue bulbs.  Using the response from @valorekhov and piecing together information from the referenced EZSP specs in the readme for [node-ezsp](https://github.com/valorekhov/node-EZSP) I was able to successfully turn on and off my bulb.

My working JSON strings:

Toggle:
`{
    "apsFrame": {
        "clusterId": 6,
        "id": 1,
        "profileId": 260,
        "sourceEndpoint": 232,
        "destinationEndpoint": 1
    },
    "message": {
        "type": "Buffer",
        "data": [
            1,
            0,
            2,
            0,
            16
        ]
    }
}`

ON:
`{
    "apsFrame": {
        "clusterId": 6,
        "id": 1,
        "profileId": 260,
        "sourceEndpoint": 232,
        "destinationEndpoint": 1
    },
    "message": {
        "type": "Buffer",
        "data": [
            1,
            0,
            1,
            0,
            16
        ]
    }
}`

OFF:
`{
    "apsFrame": {
        "clusterId": 6,
        "id": 1,
        "profileId": 260,
        "sourceEndpoint": 232,
        "destinationEndpoint": 1
    },
    "message": {
        "type": "Buffer",
        "data": [
            1,
            0,
            0,
            0,
            16
        ]
    }
}`

DIM:  ("clusterId" changes to 8 here. The 254 value in the data buffer is the brightness, (0-254) is valid)
`{
    "apsFrame": {
        "clusterId": 8,
        "id": 1,
        "profileId": 260,
        "sourceEndpoint": 232,
        "destinationEndpoint": 1
    },
    "message": {
        "type": "Buffer",
        "data": [
            1,
            0,
            4,
            254, 
            16,
            0,
            16
        ]
    }
}`

**Comment by valorekhov** [comment]
Closing as a part of migration to GitLab
